# Generated by Django 5.2.9 on 2025-12-22 17:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(max_length=120)),
                ('moviescreen', models.CharField(max_length=120)),
                ('bookingid', models.CharField(max_length=120)),
                ('theatrename', models.CharField(max_length=120)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('showtype', models.CharField(max_length=120)),
                ('dateandtime', models.DateTimeField(auto_now_add=True)),
                ('price', models.CharField(default='INR', max_length=120)),
                ('transactionid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
