# Generated by Django 5.2.9 on 2025-12-22 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='transactionid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
