# Generated by Django 5.2.9 on 2025-12-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_moviedetails_transactionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
