# Generated by Django 5.2.9 on 2025-12-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=150)),
                ('pro_price', models.IntegerField()),
                ('pro_quantity', models.IntegerField()),
            ],
        ),
    ]
